# Generated by Django 2.0.7 on 2020-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200414_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertraveldetails',
            name='route_string',
            field=models.CharField(default='ok', max_length=50),
        ),
    ]
