# Generated by Django 2.0.7 on 2020-04-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_usertraveldetails_route_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertraveldetails',
            name='route_string',
        ),
    ]
