# Generated by Django 2.0.7 on 2020-04-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20200415_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traindata',
            name='train_route_details',
        ),
        migrations.RemoveField(
            model_name='usertraveldetails',
            name='destination_station_id',
        ),
        migrations.RemoveField(
            model_name='usertraveldetails',
            name='start_station_id',
        ),
        migrations.RemoveField(
            model_name='usertraveldetails',
            name='usr',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='TrainData',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UserTravelDetails',
        ),
    ]
