# Generated by Django 2.0.7 on 2020-04-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlist',
            name='name',
            field=models.CharField(default='-', max_length=250),
            preserve_default=False,
        ),
    ]
