# Generated by Django 2.0.7 on 2020-04-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('r', 'red'), ('b', 'blue'), ('y', 'Yellow')], max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField()),
                ('train_route_details', models.ManyToManyField(to='metro.Station')),
            ],
            options={
                'verbose_name_plural': 'Train Data',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserTravelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_station', to='metro.Station')),
                ('start_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_station', to='metro.Station')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro.Users')),
            ],
            options={
                'verbose_name_plural': 'Users Travel History',
            },
        ),
    ]
